module_type = "Object"
network = "Testnet"
modules_path = [
    "libs",
    "cpu",
    "verifier",
]
addresses_name = ["lib_addr", "cpu_addr", "verifier_addr"]
private_key = "0x3d31ef06ed8003c3a85125b6e6287967a7b80a3e4367ccf2649e7acd574e4261"
yes = true
output_json = "deploy.json"
deployed_addresses = {}
publish_code = false