[package]
name = "gas-optimizer"
version = "1.0.0"
authors = []

[addresses]
lib_addr = "_"
gas_optimizer_addr = "_"
cpu_addr = "_"

[dev-addresses]
lib_addr = "54ba5979fbdf5fa56c4f4b5147fa33068148d08f6f191c23bca865c21192dcaa"
cpu_addr = "1725fb72ba62d830193fe57a932b5071c9718a44e40891e4067a2fe0e78f4d0f"
gas_optimizer_addr = "54ba5979fbdf5fa56c4f4b5147fa33068148d08f6f191c23bca865c21192dcab"

[dependencies]
libs = { local = "../libs" }
cpu = { local = "../cpu" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.17"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
